// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqjB1kaf9YgdPh92MA71sZR_UybUaPumI',
    appId: '1:572781883295:web:2dfede808d77194b8857aa',
    messagingSenderId: '572781883295',
    projectId: 'e-commerce-3af9c',
    authDomain: 'e-commerce-3af9c.firebaseapp.com',
    storageBucket: 'e-commerce-3af9c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPB3kclDjSEEXg1IaQ99qckp6E3Z-hr_U',
    appId: '1:572781883295:android:bd4859460bf819d88857aa',
    messagingSenderId: '572781883295',
    projectId: 'e-commerce-3af9c',
    storageBucket: 'e-commerce-3af9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVE4H4ZZotcP3jtl-FboPRRpUfTIo6W_E',
    appId: '1:572781883295:ios:7a3502dc8586b9b98857aa',
    messagingSenderId: '572781883295',
    projectId: 'e-commerce-3af9c',
    storageBucket: 'e-commerce-3af9c.appspot.com',
    iosClientId: '572781883295-e87kr4hhk4sf5p6qdf91sn5m8ivvv9cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVE4H4ZZotcP3jtl-FboPRRpUfTIo6W_E',
    appId: '1:572781883295:ios:7a3502dc8586b9b98857aa',
    messagingSenderId: '572781883295',
    projectId: 'e-commerce-3af9c',
    storageBucket: 'e-commerce-3af9c.appspot.com',
    iosClientId: '572781883295-e87kr4hhk4sf5p6qdf91sn5m8ivvv9cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
