// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIrye_9KjK3oG6DkBirZAkHwuft-NhSPY',
    appId: '1:865787766999:web:0e3ec285eb49555d8c2892',
    messagingSenderId: '865787766999',
    projectId: 'e-commerce-462ca',
    authDomain: 'e-commerce-462ca.firebaseapp.com',
    databaseURL: 'https://e-commerce-462ca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-462ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWBCZmj-TYn_Sroyi0vM6TizrjUBblClI',
    appId: '1:865787766999:android:5a8fc45e730a08468c2892',
    messagingSenderId: '865787766999',
    projectId: 'e-commerce-462ca',
    databaseURL: 'https://e-commerce-462ca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-462ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5-NnbPzMQVYIUif4hBdRJZ6Ilv5db8b4',
    appId: '1:865787766999:ios:778a34fd26812cbe8c2892',
    messagingSenderId: '865787766999',
    projectId: 'e-commerce-462ca',
    databaseURL: 'https://e-commerce-462ca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-462ca.appspot.com',
    iosClientId: '865787766999-44cmc1vs9ed89og2sfo0u2u767dh1jl0.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
